### ISSUE TITLE
Not an issue just a comment about a specific page on your blog

### ISSUE THREAD

**Issue by Rapidhands** [PsCustomObject/PowerShell-Functions#4]
Hi,
On your site (https://pscustomobject.github.io/powershell/howto/PowerShell-Generate-Unique-Upn/), in the part where you give a sample of use for Test-UPNExist, you write :` if ($upnExists -eq $true). `
Take care ; alway put `$true` ou `$False` on the left of the comparizon (I'm sure you know that).

See this : https://techcommunity.microsoft.com/t5/windows-powershell/powershell-how-to-use-an-if-condition-with-true-false/m-p/3598588

regards.

**Comment by PsCustomObject** [comment]
Hi many thanks for commenting :) 

Yes I'm aware of that, as I wrote in the post code is to be considered a kind of a _prototype_, matter of fact still in the Dev branch :), as I did not polish it up.

I still need to refactor the code as there are multiple parts I want to cleanup despite it being mature enough to write a post about it. 

Really appreciate your time for reading and commenting!
